import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Layout, Button, Icon } from '@/components';
import { ChartMotion, StateSharingMotion, ServerMotion, MainBannerMotion } from '@/components/motions';

const Home: NextPage = () => {
  const [bannerActive, setBannerActive] = useState(false);

  return (
    <Layout className="main_page">
      <Head>
        <title>Yorkie</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="key_visual">
        <div className="banner_img">
          <MainBannerMotion bannerActive={bannerActive} />
        </div>
        <div className="inner">
          <h2 className="title">
            <span className="text">Breathe</span>
            <span className="point">
              collaboration
              <span className="bg"></span>
            </span>
            <span className="text">your products</span>
          </h2>
          <Button.Box>
            <div className="npm_box">
              <label htmlFor="npm" className="blind">
                Npm Install
              </label>
              <input className="input" id="npm" type="text" value="$ npm install yorkie-js-sdk" readOnly />
              <Button className="gray800" blindText icon={<Icon type="copy" />}>
                copy
              </Button>
            </div>
            <Link
              href="#"
              className="btn orange_0 btn_start"
              onPointerOver={() => setBannerActive(true)}
              onPointerOut={() => setBannerActive(false)}
            >
              <span className="bg"></span>
              <Icon type="star" />
              <span className="text">Start for free</span>
            </Link>
          </Button.Box>
          <p className="desc">Open-source SDKs, Server, Database API package for real-time collaborative experiences</p>
        </div>
      </section>
      <section className="section">
        <h2 className="section_title">
          Stable.
          <br />
          Reliable.
          <br />
          Manageable.
        </h2>
        <div className="section_content">
          <ul className="horizon_list">
            <li className="horizon_item">
              <div className="img_box">
                <StateSharingMotion />
              </div>
              <div className="text_box">
                <strong className="title">Conflict-free state sharing</strong>
                <p className="desc">
                  Yorkie implements real-time collaboration based on the CRDT algorithm.
                  <br className="br_tablet" /> CRDT is formed in solid and clean architecture, effectively resolving
                  conflicts when editing multiple concurrent data.
                </p>
                <Button type="link" className="gray800" icon={<Icon type="book" />}>
                  Learn more about Yorkie SDK
                </Button>
              </div>
            </li>
            <li className="horizon_item">
              <div className="img_box">
                <ChartMotion />
              </div>
              <div className="text_box">
                <strong className="title">Real-time usage monitoring</strong>
                <p className="desc">
                  Yorkie House allows project members to browse stored documents and supervise the data warehouse
                  easily.
                </p>
                <Button type="link" className="gray800" icon={<Icon type="book" />}>
                  Learn more about Yorkie House
                </Button>
              </div>
            </li>
            <li className="horizon_item">
              <div className="img_box">
                <ServerMotion />
              </div>
              <div className="text_box">
                <strong className="title">Easy cloud server or private local server</strong>
                <p className="desc">
                  If needed, Yorkie open source packages allow you to build servers and databases locally.
                </p>
                <Button type="link" className="gray800" icon={<Icon type="book" />}>
                  How to build a local server
                </Button>
              </div>
            </li>
          </ul>
        </div>
      </section>
    </Layout>
  );
};

export default Home;
